"""Assemble the block_year fact table (DuckDB + Parquet).

Joins, per (block_uuid, assessment year):
  - INGRES quantitative assessment data (recharge, extraction, stage, rainfall)
  - PDF-parsed official categorization (the authoritative label)
  - canonical registry identity (names, district, vintage, centroid)

Emits reports/data_quality.md logging every sentinel, missing value, and
approximation (CLAUDE.md non-negotiable #5: never silently impute).
"""

from __future__ import annotations

import json
from pathlib import Path

import duckdb
import pandas as pd

RAW = Path("data/raw")
OUT = Path("data/processed")
REPORTS = Path("reports")

# INGRES year label -> (PDF/GWRA year, boundary vintage)
YEARS = {
    "2016-2017": ("2017", 2019),
    "2019-2020": ("2020", 2019),
    "2021-2022": ("2022", 2021),
    "2022-2023": ("2023", 2021),
    "2023-2024": ("2024", 2021),
    "2024-2025": ("2025", 2021),
}

STAGE_SENTINEL = -1000.0  # INGRES uses large negative sentinels for no-data/saline

CATEGORY_ORDINAL = {"safe": 0, "semi_critical": 1, "critical": 2, "over_exploited": 3}


def load_quantitative() -> pd.DataFrame:
    frames = []
    for ingres_year, (gwra_year, vintage) in YEARS.items():
        rows = [json.loads(line) for line in open(RAW / f"ingres/raj_blocks_{ingres_year}.jsonl")]
        df = pd.DataFrame(rows)
        df["gwra_year"] = gwra_year
        df["year"] = int(gwra_year)
        df["vintage"] = vintage
        frames.append(df)
    q = pd.concat(frames, ignore_index=True)
    q = q.rename(columns={"location_uuid": "block_uuid", "stage_of_extraction_pct": "stage_pct"})
    return q


def build() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    REPORTS.mkdir(parents=True, exist_ok=True)

    q = load_quantitative()
    cat = pd.read_parquet(OUT / "block_categories.parquet")[
        ["block_uuid", "gwra_year", "category", "match_score", "how"]
    ]
    reg = pd.read_csv(OUT / "canonical_blocks.csv")[
        ["block_uuid", "block_name", "district_name", "vintage", "centroid_lon", "centroid_lat"]
    ]

    panel = q.merge(cat, on=["block_uuid", "gwra_year"], how="left").merge(
        reg, on=["block_uuid", "vintage"], how="left", validate="many_to_one"
    )

    # station depth seasons (CGWB bulk, 2013-2023) — joins where years overlap;
    # the full series lives in block_depth_seasons.parquet for M1-depth
    depth_path = OUT / "block_depth_seasons.parquet"
    if depth_path.exists():
        dep = pd.read_parquet(depth_path)[
            ["block_uuid", "year", "premonsoon_depth_m", "postmonsoon_depth_m",
             "seasonal_recovery_m", "n_stations_pre"]
        ]
        panel = panel.merge(dep, on=["block_uuid", "year"], how="left")

    # sentinel handling: flag, then NULL — never a fabricated number
    n_sentinel = int((panel["stage_pct"] < STAGE_SENTINEL).sum())
    panel["stage_sentinel_flag"] = panel["stage_pct"] < STAGE_SENTINEL
    panel.loc[panel["stage_sentinel_flag"], "stage_pct"] = None

    panel["category_ordinal"] = panel["category"].map(CATEGORY_ORDINAL)
    panel["extraction_over_recharge_pct"] = (
        100.0 * panel["extraction_total_ham"] / panel["recharge_total_ham"]
    ).where(panel["recharge_total_ham"] > 0)

    cols = [
        "block_uuid", "block_name", "district", "district_name", "vintage",
        "centroid_lon", "centroid_lat", "year", "gwra_year",
        "category", "category_ordinal", "match_score", "how",
        "rainfall_mm",
        "recharge_total_ham", "recharge_rainfall_ham", "recharge_canal_ham",
        "recharge_surface_irrigation_ham", "recharge_gw_irrigation_ham",
        "recharge_water_body_ham", "recharge_artificial_ham",
        "loss_total_ham", "extractable_ham",
        "extraction_agriculture_ham", "extraction_domestic_ham",
        "extraction_industry_ham", "extraction_total_ham",
        "stage_pct", "stage_sentinel_flag", "extraction_over_recharge_pct",
        "future_availability_ham", "allocation_domestic_ham",
        "area_recharge_worthy_ha", "area_total_ha",
        "premonsoon_depth_m", "postmonsoon_depth_m", "seasonal_recovery_m",
        "n_stations_pre",
    ]
    cols = [c for c in cols if c in panel.columns]
    panel = panel[cols].sort_values(["year", "district_name", "block_name"])

    panel.to_parquet(OUT / "block_year.parquet", index=False)
    con = duckdb.connect(str(OUT / "jal.duckdb"))
    con.execute("CREATE OR REPLACE TABLE block_year AS SELECT * FROM panel")
    con.close()

    write_quality_report(panel, n_sentinel)
    print(f"block_year: {len(panel)} rows -> {OUT}/block_year.parquet + jal.duckdb")


def write_quality_report(panel: pd.DataFrame, n_sentinel: int) -> None:
    lines = [
        "# Data quality report — block_year panel",
        "",
        f"Generated by `jal.panel.build`. Rows: **{len(panel)}** "
        f"({panel.block_uuid.nunique()} blocks x {panel.year.nunique()} assessment years).",
        "",
        "## Provenance",
        "- Quantitative fields: INGRES verified assessments (see data/raw/ingres/SOURCE.md)",
        "- `category`: parsed from CGWB block-wise categorization PDFs (authoritative label;",
        "  see data/raw/cgwb_assessment/SOURCE.md); reconciliation in src/jal/reconcile/",
        "",
        "## Sentinels and NULLs (no silent imputation — non-negotiable #5)",
        f"- `stage_pct` sentinel values (INGRES no-data/saline, < {STAGE_SENTINEL}): "
        f"**{n_sentinel}** rows -> set NULL, `stage_sentinel_flag=true`",
        "",
        "## Missingness by column (count of NULLs)",
        "",
        "| column | nulls | % |",
        "|---|---|---|",
    ]
    for c in panel.columns:
        n = int(panel[c].isna().sum())
        if n:
            lines.append(f"| {c} | {n} | {100 * n / len(panel):.1f}% |")
    lines += [
        "",
        "## Station depth integration (D1-2)",
        "- CGWB station depths (India Data Portal bulk): 1,394 stations, 2013-2023,",
        "  79% of blocks with >=6 pre-monsoon seasons. Joined into block_year where",
        "  assessment years overlap (2017, 2020); full series in",
        "  block_depth_seasons.parquet. Block value = median of in-polygon stations.",
        "- COVID monitoring gap (documented, not imputed): pre-monsoon campaign",
        "  collapsed in 2020 (183 readings vs ~1,000 typical) and 2021 (115) during",
        "  lockdowns; 2020 panel depth coverage is therefore 3 blocks vs 248 in 2017.",
        "",
        "## Known approximations and caveats",
        "- GWRA 2024/2025 categorization PDFs omit the 3 saline blocks -> `category` NULL",
        "  for those block-years (INGRES quantitative rows retained, flagged via NULL).",
        "- Assessment years are irregular (2017, 2020, 2022, 2023, 2024, 2025); models use",
        "  explicit year gaps, never assume annual spacing.",
        "- Pre-2023 assessments use the 2019 boundary vintage (295 blocks); 2022+ use the",
        "  2021 vintage (302 blocks). Cross-vintage block continuity is handled by uuid",
        "  where CGWB kept the unit, and flagged as new/discontinued otherwise.",
        "- `match_score`/`how` record how each category row was matched (fuzzy >= 0.95 or",
        "  curated override).",
    ]
    cat_cov = panel.groupby("year")["category"].apply(lambda s: int(s.notna().sum()))
    lines += ["", "## Category coverage by year", "", "| year | rows with category |", "|---|---|"]
    for y, n in cat_cov.items():
        lines.append(f"| {y} | {n} |")
    Path(REPORTS / "data_quality.md").write_text("\n".join(lines) + "\n")
    print(f"data quality report -> {REPORTS}/data_quality.md")


if __name__ == "__main__":
    build()
